[tool.robotpy]

robotpy_version = "2025.3.2.1"

robotpy_extras = [
    "apriltag",
    "commands2",
    "cscore"
]

# Other pip packages to install
requires = [
    "phoenix6==25.3.1",
    "robotpy-opencv; platform_machine == 'roborio'",
    "opencv-python; platform_machine != 'roborio'"
]
